#!/usr/bin/env bash

# Environment Flags
set -o errexit  # Exit when a command fails
set -o pipefail # Catch mysqldump fails
set -o nounset  # Exit when using undeclared variables

# FOLDER="$(readlink -f "${BASH_SOURCE[0]}" | xargs dirname)"

if [[ ! -d "./node_modules" ]]; then
    npx --yes bun@latest install >/dev/null
fi

npx --yes bun@latest run "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/cli.ts" -- "$@"