name: Publish Package to npm

on:
  push:
    tags:
    - 'v*.*.*' # Trigger on tags like v1.0.0, v1.2.3, etc.

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the code

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Setup Node.js for npm publish
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org/'

    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
