name: Publish Package to npm

on:
  push:
    tags:
    - 'v*.*.*' # Trigger on tags like v1.0.0, v1.2.3 etc.

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to check out the code

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest # Or specify a version

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Build package
      run: bun run build

    - name: Copy package.json to dist
      run: cp package.json ./dist/

    - name: Copy README.md to dist
      run: cp README.md ./dist/

    - name: Setup Node.js for npm publish
      uses: actions/setup-node@v4
      with:
        node-version: '20.x' # Use a specific LTS version
        registry-url: 'https://registry.npmjs.org/'
        # scope: '@first-to-fly' # Optional: Define scope if needed for .npmrc

    - name: Publish to npm
      working-directory: ./dist # Run npm publish from the build output directory
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use the secret token
